using System.Runtime.InteropServices;

namespace Jay.GhostInput.Native.Structs
{
	/// <summary>
	/// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
	/// </summary>
	[StructLayout(LayoutKind.Sequential)]
	internal struct HardwareInput
	{
		/// <summary>
		/// The message generated by the input hardware.
		/// </summary>
		internal int uMsg;

		/// <summary>
		/// The low-order word of the lParam parameter for uMsg.
		/// </summary>
		internal ushort wParamL;

		/// <summary>
		/// The high-order word of the lParam parameter for uMsg.
		/// </summary>
		internal ushort wParamH;
	}
}
