using Jay.SourceGen.CodeBuilding;
using Xunit;

namespace Jay.SourceGen.Tests;

public class SourceCodeBuilderTests
{
    [Fact]
    public void AnythingWorks()
    {
        using var code = new SourceCodeBuilder();
        code.AutoGeneratedHeader()
            .Using("System.Text")
            .Namespace("Jay.Testing")
            .Code
    }
}